### ISSUE TITLE
[new feature] skip iterations X-Y

### ISSUE THREAD

**Issue by stas00** [bigscience-workshop/Megatron-DeepSpeed#175]
We need a new feature to skip iterations.

Adding a flag:

`--skip-iteration-range <first-iterA>-<last-iterA> <first-iterB>-<last-iterB> <first-iterC>-<last-iterC>` 

in other words the range is defined by a single arg of `start-stop` and can be listed multiple times.

Since we are counting iterations from 1 here, the above range is literal and not 0-index based. i.e. `stop` is part of the range to exclude.

So we may have a training with:

`--skip-iterations  11001-11101 13001-13101`

1. These ranges would be plugged into the training loop. It should very simple of just `continue`-ing while in the skipped range without doing the normal iteration code.

2. But one nuance is that we want these to be updated:
```
         args.consumed_train_samples = correct_number_of_trained_samples
         args.consumed_valid_samples = correct_number_of_validated_samples
```

and of course the iteration counter to correctly incremented as if the iterations did run.

3. Additionally indicate that this range was skipped with printing on rank 0 of the range that was skipped. e.g.:
```
Skipped iterations 11001 11101 due to --skip-iterations flag.
```

4. The side-effect of iterations being skipped is that TB will have a gap in the graph. Not 100% sure about this one.

I think we want to support multiple ranges. Especially if we want to re-train with the same setup.

5. need a test - should be easy by capturing STDOUT and checking that the skipped iterations aren't there in the log but any before and after the range are reported. so check one before the range, one after and one in the middle. (remember we have a context manager in `testing_utils.py` for that. set `--log-interval 1` in that test.

Application:

Say we got a huge spike at iteration 11000 and we want to try to overcome it by skipping the data that we believe led to the spike, say the next 100 iterations.

1. we roll-back to the last good checkpoint
2. we resume the training normally but with `--skip-iterations  11001-11101`

since we are counting iterations from 1 here, the above range is literal and not 0-index based. That is the training will continue normally at iteration 11102.

Then later down the road we may encounter another spike and add another range to skip, keeping the existing one already in place. That will allow us to replicate the training exactly with new configuration.

@jaketae

**Comment by jaketae** [comment]
I assume this is where we want to add some checks for the `continue`.

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/5e1f21017d8d05fdc1d031e991878ef36f9f792c/megatron/training.py#L722-L723

I imagine I will have a list of start and end iterations for each interval.

```python
# -skip-iteration-range 11000-11010 11020-11030 ...
starts = [11000, 11020, ...]
ends = [11010, 11030, ...]
```

Inside the `while`, I would do

```python
# import bisect

idx = bisect.bisect_left(starts, iteration)
if iteration <= ends[idx]:
    continue
```

This assumes that the intervals are inclusive. 

I will try to familiarize myself with nuances of the counter logic. Thanks!

**Comment by stas00** [comment]
I'd code it before that loop, so not to make things more complex. But if it works better in the training loop that's fine too.

But it looks like the task is slightly more complex, since you want to `continue` but you need to drain `data_iterator` by the exact amount of data to be skipped. otherwise nothing is accomplished.

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/5e1f21017d8d05fdc1d031e991878ef36f9f792c/megatron/training.py#L405
 
So you need to follow `train_batch` into deepspeed and figure out how to iterate over the dataloader to move its internal iteration counters forward. 

Please let me know if it makes sense. There are probably other nuances that you will discover will be needed.

And then you need to run this code (so 2 counters there, one new one that is not described in OP):

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/5e1f21017d8d05fdc1d031e991878ef36f9f792c/megatron/training.py#L747-L751

it's probably ok to leave the validation counters alone, as these don't matter in this situation.

**Comment by stas00** [comment]
I wonder if the new arg should be called `--skip-train-iteration-range` since we really are just dealing with train here.

**Comment by jaketae** [comment]
> But it looks like the task is slightly more complex, since you want to `continue` but you need to drain `data_iterator` by the exact amount of data to be skipped. otherwise nothing is accomplished.

This makes sense. 

I'm curious to hear what your thoughts are on a "hack." Instead of calling `model[0].train_batch(data_iter)`, what if we just call `model[0].eval_batch(data_iter)`? We wouldn't be backpropagating, so it won't affect training. I guess the TB logs could plot somewhat misleading values.

I will continue to look at DS to figure out how `data_iter` if flushed, but it doesn't seem to be as simple as `next(data_iter)` and it might be deep in the code. I'll keep you posted.

**Comment by stas00** [comment]
> what if we just call model[0].eval_batch(data_iter)

I don't think it is the best approach for reason yous mentioned, plus it'd actually have to run through all those iterations.

> but it doesn't seem to be as simple as next(data_iter), 
 
I think it should be as simple as `next(data_iter)` except you need to figure out how many times to call it to accommodate for DP.

or perhaps we could offer a patch to Deepspeed that `train_batch` could take a new argument `train_batch(..., skip_train_logic=False)` so that it'd allow users to call `train_batch` and it'd pull the data but leave the train logic unactivated

>  Upon closer examination, maybe they aren't using the same amount of data in training and eval.

They are using the same seqlen, that's why I suggested that `next(data_iter)` may do the trick. but you need to deal with DP.

The dataloader is already preconfigured, but it doesn't use the same dataloader for train and valid.

**Comment by stas00** [comment]
@jaketae,

OK, so it's simple at the end, all you need is to insert in `training.py:train()`, before the main train loop

```
if args.skip_n_batches > 0 and train_data_iterator is not None:
        for skip_batch in range(args.skip_n_batches):
            ignore_data = next(train_data_iterator)
```

Courtesy of @ShadenSmith - Thank you, Shaden!

We just need to translate it to our start/stop api.

**Comment by jaketae** [comment]
@stas00 So it was indeed just `next(train_data_iterator)` after all!

I assume `args.skip_n_batches` is just the number of batches to skip. But in our case, we will be specifying the range to skip, right? So to sum up:

* Modify `get_args()` to be able to handle `--skip-iteration-range <first-iterA>-<last-iterA> <first-iterB>-<last-iterB>`
* Call `next(train_data_iteration)` in https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/5e1f21017d8d05fdc1d031e991878ef36f9f792c/megatron/training.py#L722-L723 after checking that the current `iteration` falls within some range specified by the argument
* Adapt to start/stop API?

I'm not entirely sure on the last part, but I'll get started on the first two bullet points and open a PR.

**Comment by stas00** [comment]
Yes, that's how they implemented it. I think an explicit range implementation as I proposed it is easier on the operator if you know you want to skip a particular range, rather than calculating the gap and also not being sure whether the edges are inclusive or not. So let's stick to our spec. 

I'm not sure about DP, should be easy to test with 2 gpus and a no PP/TP so that the whole model fits on a single GPU. It's possible that there is no need to be concerned with DP. I'm just not familiar with that section of the code. Hence you can either study the code or simply test it. e.g. dump the first 10 items of each dataloader batch and compare if it's the same with DP=1 vs DP=2.

What's a start/stop API? If you are referring to `skip_n_batches` vs `start-stop` range - they are exactly the same. Whatever make the code more readable.

But if you directly drain the dataloader as Shaden did, you don't go into the while loop you quoted, you drain the dataloader before the loop is reached.

Going into the loop would have worked if we were using the `continue` method we discussed at the beginning, but as you have found out it would be complicated, since the dataloader is accessed many frames deeper.

**Comment by jaketae** [comment]
Apologies for making you repeat, but I don't quite understand how the code snippet would work outside of the `while` loop. If the operator specifies they want to skip iterations from `100-110 150-160`, wouldn't we need to access the `iterator` variable inside the `while` loop as it is getting updated? 

I guess my point of confusion is how the following code would work.

```python
# args.skip_train_iteration_range is parsed as [[100, 110], [150, 160]]
if args.skip_train_iteration_range is not None and train_data_iterator is not None:
    for (start, end) in args.skip_train_iteration_range
            ignore_data = next(train_data_iterator)
while iteration < args.train_iters and (args.train_tokens is None or \
    args.consumed_train_tokens < args.train_tokens):
    # do stuff
```

The `start` and `end` variables are completely ignored. What I had in mind was something like

```python
while iteration < args.train_iters and (args.train_tokens is None or \
        args.consumed_train_tokens < args.train_tokens):
        if (
            args.skip_train_iteration_range is not None 
            and iteration == args.skip_train_iteration_range[0][0]
        ):
            _, end = args.skip_train_iteration_range.popleft()
            while iteration <= end:
                for _ in range(args.skip_n_batches):
                    _ = next(train_data_iterator)
                iteration += 1
            continue
```

**Comment by stas00** [comment]
This is untested, but to add to your code:

```
# args.skip_train_iteration_range is parsed as [[100, 110], [150, 160]]

if args.skip_train_iteration_range is not None and train_data_iterator is not None:
    for (start, end) in args.skip_train_iteration_range:
            _ = next(train_data_iterator)
            iteration += 1
            args.consumed_train_samples += new_samples # need to figure out 
            args.consumed_train_tokens += new_tokens # need to figure out 
 
while iteration < args.train_iters and (args.train_tokens is None or \
    args.consumed_train_tokens < args.train_tokens):
    # do stuff
```

**Comment by jaketae** [comment]
Is "drain intervals 100 to 110, and 150 to 160" the same as "drain 20 iterations worth of data in total"? I was under the impression that they would be different, which is why I was thinking of something like

```python
# args.skip_train_iteration_range is parsed as deque([[100, 110], [150, 160]])

while iteration < args.train_iters and (args.train_tokens is None or \
    args.consumed_train_tokens < args.train_tokens):
    if (
        args.skip_train_iteration_range is not None 
        and iteration == args.skip_train_iteration_range[0][0]
    ):
        _, end = args.skip_train_iteration_range.popleft()
        while iteration <= end:
            _ = next(train_data_iterator)
           args.consumed_train_samples += new_samples # need to figure out 
           args.consumed_train_tokens += new_tokens # need to figure out 
            iteration += 1
        continue
```

**Comment by stas00** [comment]
Good point indeed. The multiple ranges won't work outside of the main loop. Nice catch, Jake!
