### ISSUE TITLE
Refactor existing tests to use variations

### ISSUE THREAD

**Issue by jaketae** [bigscience-workshop/Megatron-DeepSpeed#181]
To improve readability and avoid boilerplate duplicates, it'd be best to refactor `test_training_prefix_lm_all` in [`test_train.py`](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/tests/test_training.py#L221)  to use decorators as follows. This was brought up in https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/177#discussion_r743183926

This is likely low priority.

**Comment by stas00** [comment]
If over time we find that we need a different granularity we can then further refactor things. So there could be 2-3 different boiler plates and different tests choosing which of them is the closest. 

i.e. we don't have to make everything go through the same engine.

The goal is easy maintenance while maintaining relatively easy readability. If the latter is lost then it's not great either and a different approach should be sought.

**Comment by jaketae** [comment]
Closing this issue to declutter/give better visibility to other issues that require attention. Feel free to re-open if you see this as a problem @stas00. Thank you!
