### ISSUE TITLE
Add progress percentage on TBs

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/Megatron-DeepSpeed#183]
We should have a view that tells you the % of the training done -> I am looking at a random TB, how far is the training? 10%? 40%? 90%?
It's more or less comparing `global_step` (or whatever it is called) against the number of training steps

**Comment by stas00** [comment]
but iterations is not a very useful metric to get a feel of the progress, because of various rampups. 

Perhaps % tokens completed is a much more realistic estimate?

**Comment by VictorSanh** [comment]
that's a good point, yes!

**Comment by stas00** [comment]
On the other hand we don't really know the total tokens. It'd take some figuring out to calculate that because of all the moving hparams.

On the other hand it's pretty obvious where you're at for iterations by looking at the logs, e.g.:
```
iteration     2861/  159576
```
Is it hard to tell that it's barely starting?

Perhaps we could log a % next to these 2 numbers? e.g.:

```
iteration     2861/  159576 (0.02%)
```

or do you want TB?

**Comment by jaketae** [comment]
If it's just the % of iterations completed, it should be very quick, and I can take it. If there is more consensus around what needs to be logged where (e.g. % tokens on TB), I can try that as well, although I'd imagine it might take more time.

**Comment by stas00** [comment]
I think it should be % of total tokens, since that's the only things that's constant. e.g. CL has a very different way of progressing on GBS+seqlen than non-CL. the former is fixed GBS, and ramping up seqlen, the latter ramping up GBS, and fixed seqlen.

**Comment by VictorSanh** [comment]
Yes agree, i think % of tokens is the right metric to display as the other things move too much between experiments

**Comment by VictorSanh** [comment]
We automatically report `consumed tokens` in the log so I presume that's the numerator you want to track

```bash
 iteration   129800/  296023 | consumed samples:     61377984 | consumed tokens: 114608308224 | elapsed time per iteration (ms): 3003.7 | learning rate: 1.294E-04 | global batch size:   512 | lm loss: 1.904025E+00 | loss scale: 262144.0 | grad norm: 19558.385 | num zeros: 0.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
```

**Comment by jaketae** [comment]
@VictorSanh Thank you. I think I'll just have to figure out some math to calculate the total number of tokens and put that in the denominator.
