### ISSUE TITLE
Try the multi-dataset setup with sampling probabilities

### ISSUE THREAD

**Issue by ibeltagy** [bigscience-workshop/Megatron-DeepSpeed#20]
Multilingual models are trained on multiple datasets (one dataset per language) with a sampling probability for each dataset. 

This feature (training on instances randomly sampled from multiple dataset files) seems to be supported in our Megatron code base (check here https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/run.sh#L9-L12, thanks to @sbmaruf for finding it), but we want to give it a try and make sure it is working with multiple gpus on multiple nodes. For testing, we can do the following: 
- create a few small datasets. Don't preprocess a huge dataset because it takes forever. All datasets can be English if it is easier but make sure each dataset is recognizable from its data (for logging)
- start training a multi-node model
- add logging to verify that the sampling probabilities are respected

Once we verify this feature is working, we will swap the small testing datasets with the preprocessed multilingual datasets for the real training. 

Here are the instructions for how to get started with the code-base
```
- install things: https://github.com/bigscience-workshop/Megatron-DeepSpeed#setup
- get and preprocess data to work with: https://github.com/bigscience-workshop/Megatron-DeepSpeed#quick-pre-processing-to-start-training-with
- train: https://github.com/bigscience-workshop/Megatron-DeepSpeed#gpt-pretraining
```

**Comment by lintangsutawika** [comment]
Please assign this to me.

**Comment by ontocord** [comment]
Would you consider changing the preprocess_data script to actually create the combined multilingual dataset with sampling at that point. We could also do same basic preprocessing like langid? @thomasw21 are working on optimizing preprocessing.

**Comment by ibeltagy** [comment]
@ontocord, we believe it is better to keep the preprocessed files for each language separate to make it easy to change the sampling probabilities at training time.

**Comment by lintangsutawika** [comment]
I have verified that each dataset can be sampled according to the given ratio. I made a dummy dataset and gave arbitrary ratio and process each batch when it's loaded.

This is a part of the script for setting up the datasets
```
DATASET_0="/workspace/data/dataset-0_text_document"
DATASET_1="/workspace/data/dataset-1_text_document"
DATASET_2="/workspace/data/dataset-2_text_document"
DATASET_3="/workspace/data/dataset-3_text_document"
DATASET_4="/workspace/data/dataset-4_text_document"
# DATASET_5="/workspace/data/dataset-5_text_document"
# DATASET_6="/workspace/data/dataset-6_text_document"
# DATASET_7="/workspace/data/dataset-7_text_document"
# DATASET_8="/workspace/data/dataset-8_text_document"
# DATASET_9="/workspace/data/dataset-9_text_document"
DATASET="0.1 ${DATASET_0} 0.25 ${DATASET_1} 0.2 ${DATASET_2} 0.15 ${DATASET_3} 0.3 ${DATASET_4}"
```

This is the last printed output after training as finished.
```
{'dataset_4': 5184, 'dataset_1': 4320, 'dataset_2': 3456, 'dataset_3': 2592, 'dataset_0': 1728}
------------------------------------------------------------------------------------------------------------------
 validation loss at the end of training for val data | lm loss value: 2.502806E-02 | lm loss PPL: 1.025344E+00 |
------------------------------------------------------------------------------------------------------------------
```

**Comment by lintangsutawika** [comment]
I have created a pull request for this here #36
