### ISSUE TITLE
Print arguments in a seperate file

### ISSUE THREAD

**Issue by thomasw21** [bigscience-workshop/Megatron-DeepSpeed#214]
Currently we log the arguments used (the lines right after `------------------------ arguments ------------------------`) in stdout that we catch inside `main_log.txt`.

I think we should also store them in a seperate file to check the config seperatly.

**Comment by arovn10** [comment]
Hi! I may be of help with your issue. Can you assign me so I can take a look?

**Comment by thomasw21** [comment]
@bhavitvyamalik has opened a PR for this.

**Comment by bhavitvyamalik** [comment]
Can we close this now @thomasw21?
