### ISSUE TITLE
Setup a relatively simple evaluation benchmark

### ISSUE THREAD

**Issue by ibeltagy** [bigscience-workshop/Megatron-DeepSpeed#22]
We need an evaluation benchmark that we can use for iterating on the model design. It needs to satisfy the following requirements: 
- Two versions: English-only and multilingual
- Zero-shot, few-shot, and many-shots: it should include at least the first two (the third is debatable)
- Works on Megatron checkpoints and hugginface/transformers checkpoints. The modeling group will make a Megatron checkpoint available soon. In the meantime, you can start using hugginface/transformers checkpoints, for example, this one https://huggingface.co/gpt2
- Easy to run: ideally a single script that reads the checkpoint and outputs the evaluation results
- Doesn't take too long to run: anything longer than 1 day on 1 gpu is too much
- Representative: it covers the key tasks (LM, QA, classification, generation .. anything else?)

Update 

- Assume the model is autoregressive and it uses causal language modeling
- Selected datasets need to make it possible to compare with existing pretrained models (e.g. GPT3, GPT-J, mT5 ... )

**Comment by sbmaruf** [comment]
@ibeltagy We should also fill up [this](https://github.com/huggingface/lm-evaluation-harness) chart each time we train a new model. This is relatively simple to perform.
If you don't want to do the full list, we can also consider a subset of them. 
https://blog.eleuther.ai/gpt3-model-sizes/
