### ISSUE TITLE
misreporting GFLOPs as TFLOPs

### ISSUE THREAD

**Issue by stas00** [bigscience-workshop/Megatron-DeepSpeed#221]
Both the TB `iteration-time/TFLOPs per gpu (estimated)` and the logs currently misreport GFLOPs as TFLOPs, e.g.:

```
 iteration     9639/  292968 | ... | TFLOPs: 30949.01 |
```

That should be either:

- `GFLOPs: 30949.01`
- `TFLOPs: 30.95`

Probably the latter is the easiest to read since we want TFLOPs.

@jaketae, if you'd like to have a look at where we are not diving by 1024.

Thanks!

**Comment by jaketae** [comment]
Hello @stas00, thank you for opening this issue. I'll take a look at it and follow up with you if anything is unclear!

**Comment by bhavitvyamalik** [comment]
I just had a quick look at the training code and found that the `tflops` value is not divided by `1e-3` 
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/4ed19efb2c50ecc35f693360e2488a5cf3e4ca6d/megatron/training.py#L683

but the formula mentioned few lines above suggests dividing by `1e-3`
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/4ed19efb2c50ecc35f693360e2488a5cf3e4ca6d/megatron/training.py#L675

**Comment by stas00** [comment]
Thank you for investigating, @bhavitvyamalik!

Yes, we need to add `*1e3` as in the formula.

Adding here. https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/223

**Comment by stas00** [comment]
So CL is still not reporting the right thing here, as it's seqlen is not fixed.
