### ISSUE TITLE
Likely bug in Alibi positional embeddings together with Tensor Parallelism.

### ISSUE THREAD

**Issue by DanielHesslow** [bigscience-workshop/Megatron-DeepSpeed#227]
The way alibi is implemented we first generate the alibi attention bias tensor 
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/7ab5c05ad2e3b4ee678307260c62e89ab592505a/megatron/model/transformer.py#L591
and then extract the part of it:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/7ab5c05ad2e3b4ee678307260c62e89ab592505a/megatron/model/transformer.py#L291

When we run with tensor parallelism, the attention heads will be distributed. We then need to extract the correct part of alibi tensor corresponding to our tensor parallel rank. 

In order to fix this we need to:
1. Create a test that makes sure that we get the same output with and without tensor parallelism. 
2. Extract the correct part of the alibi_tensor corresponding to our tensor_parallel rank.

**Comment by thomasw21** [comment]
@stas00 for visibility in case we're going for Alibi and TP > 1

**Comment by stas00** [comment]
After yesterday's call we are definitely going for TP=8.

And it does sounds like we are going for Alibi - at least that's what @ibeltagy said in the channel.

**Comment by ibeltagy** [comment]
Yes, we certainly want to use ALiBi in the final model, and we need to fix the ALiBi/TP bug.

**Comment by DanielHesslow** [comment]
Closing this since the fix has been unit tested and is now merged into main.
