### ISSUE TITLE
Check all EAI Eval tasks

### ISSUE THREAD

**Issue by thomasw21** [bigscience-workshop/Megatron-DeepSpeed#228]
We've observed some tasks not learning at all over the first 100B tokens during pretraining. One of the suspicion we have is some tasks are bugged.

The current task list we run:

```python
arc_challenge,arc_easy,boolq,copa,headqa_en,hellaswag,lambada,logiqa,mathqa,mc_taco,mrpc,multirc,openbookqa,piqa,prost,pubmedqa,qnli,qqp,race,rte,sciq,sst,triviaqa,webqs,wic,winogrande,wnli,wsc
```

Done when
 - [ ] review all individual task making sure that they are coherent.
 - [ ] re-run evaluation on those task
 - [ ] start tracking task version correctly.

**Comment by thomasw21** [comment]
@zphang I vaguely remember you mentioning you might be interested in taking this task? There should be quite some intersection with https://github.com/EleutherAI/lm-evaluation-harness/issues/248

**Comment by zphang** [comment]
Yep. I've checked from most of them (ex: prost, pubmedqa, webqs, which have datasets versioning issues I think. Race does as well). Pinning the datasets commit as Lucile mentioned should help as well.

**Comment by zphang** [comment]
Documenting the tasks with examples: https://hackmd.io/wBpmKPKBSZKm-icYcLaFgw?view

Still missing prost, pubmedqa, webqs as mentioned above.

**Comment by thomasw21** [comment]
Do we close this then?
