### ISSUE TITLE
Wrong unit for throughput logging

### ISSUE THREAD

**Issue by janEbert** [bigscience-workshop/Megatron-DeepSpeed#236]
When calculating the samples or tokens per supposed second for logging, [the `elapsed_time_per_iteration` is multiplied by 1000](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/04c461ed786ed0e257690e136d3481957b0ef582/megatron/training.py#L669), changing the unit to be milliseconds instead.

---

The rest here is just for background to be sure I got the units right:

As [the timers work with `time.time()`](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/04c461ed786ed0e257690e136d3481957b0ef582/megatron/global_vars.py#L284), I assumed that `elapsed_time_per_iteration` has the unit "seconds".

The same [`elapsed_time_per_iteration` is also later multiplied by 1000 for logging in milliseconds](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/04c461ed786ed0e257690e136d3481957b0ef582/megatron/training.py#L711-L712).

**Comment by stas00** [comment]
Indeed. Let's see what needs to be fixed and whether it's important.

The log file says: `elapsed time per iteration (ms): 3461.3` - i.e. ms - no error there.

So the variable name `samples_per_sec` is misleading (and the rest derived from it)

Anything else?

It'd be tricky to switch to seconds with all the trainings on the way as it'd screw up all the existing TBs, but we could also try to fix up the TB files.

**Comment by janEbert** [comment]
I was really only interested in the throughput numbers, so I can't say confidently whether those are the only affected logs. :)

Sorry, I should have described more clearly which variables I was talking about. It is as you said that `samples_per_sec` and derivations are affected (`samples_per_sec_per_replica`, `tokens_per_sec`, `tokens_per_sec_per_replica` are the only ones as far as I can tell).

It's also not only the variable name that's misleading as you implied, but also the log strings state that the unit is "seconds" (see [TB logging](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/e9750c42f43f7eefccf4d534552b4c6b52b179aa/megatron/training.py#L694-L701) and [text logging](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/e9750c42f43f7eefccf4d534552b4c6b52b179aa/megatron/training.py#L736)).

So depending on if you'd rather keep (a) the strings or (b) the numeric values the same as before, you could either
a) adjust the variable names and log strings to say "ms" instead of "seconds", or
b) remove [the multiplication by 1000 when calculating `samples_per_sec`](https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/04c461ed786ed0e257690e136d3481957b0ef582/megatron/training.py#L669).

I'd suppose fixing up the TB files is possible by building on something like [this StackOverflow answer](https://stackoverflow.com/a/60080531).

**Comment by stas00** [comment]
I think you have probably covered all the bases.

> I'd suppose fixing up the TB files is possible by building on something like this StackOverflow answer.

Yes, I already adapted that SO answer to rename TB entries. https://gist.github.com/stas00/4cd1651d1c8f01196ea322c733bde46c

So it can be cloned and used to rescale those numbers.

Would you be interested to work on a PR that fixes this issue and optionally a script to rescale those TB entries that are already in the TB files?

**Comment by janEbert** [comment]
>> I'd suppose fixing up the TB files is possible by building on something like this StackOverflow answer.
>
> Yes, I already adapted that SO answer to rename TB entries. https://gist.github.com/stas00/4cd1651d1c8f01196ea322c733bde46c
>
> So it can be cloned and used to rescale those numbers.

That's perfect! Would gladly open a PR; just to be crystal clear, since you talked about rescaling, I'll go with option a, removing the multiplication that converts from seconds to milliseconds.

Thanks for a nice code basis as always, by the way.
