### ISSUE TITLE
Train prefix-lm model

### ISSUE THREAD

**Issue by ibeltagy** [bigscience-workshop/Megatron-DeepSpeed#24]
TODO: fill in details

**Comment by ibeltagy** [comment]
https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/21 is implementing the mask while this one is training the model.

**Comment by ontocord** [comment]
I think we are doing pretraining as part of impelmenting the prefix-lm masking now, right @thomasw21? So maybe we can close this issue and change https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/21 to "Implement prefix-lm as in the T5 paper & train prefix-lm model"
