### ISSUE TITLE
Limit cache for GPT2Tokenizer

### ISSUE THREAD

**Issue by thomasw21** [bigscience-workshop/Megatron-DeepSpeed#35]
After some OOM errors when preprocessing large files, I noticed that the caching mechanim can have unlimited memory due to its ability to grow forever. This causes issues, in particular in multiprocessing cases when this cache is multiplied by the number of workers. This prevents to work with large datasets.

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/781676b59d28c5f4b6fd155fcbf15026991d2187/megatron/tokenizer/gpt2_tokenization.py#L167

Note: I've tried switching to HF tokenizer, and the memory constraint becomes much lower since it doesn't cache.

In order to reduce the memory constraint, we can either:
 - implement a limited memory cache (LRU or something like that)
 - shared cache between workers
 - remove cache mechanism
 - ignore the problem since we'll use another implementation of tokenizer

cc @ontocord

**Comment by ontocord** [comment]
@thomasw21, the code we tested also has LRU cache of 1M items, so this should fix the issues.

**Comment by ontocord** [comment]
Closed by https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/37
