### ISSUE TITLE
fintuning bloom 176b with bitfit

### ISSUE THREAD

**Issue by drxmy** [bigscience-workshop/Megatron-DeepSpeed#359]
I saw there is a branch with bitfit and wonder how much VRAM it will use to fintune bloom-176b. @Muennighoff

Thank you

**Comment by Muennighoff** [comment]
Hey! Not sure about how much VRAM it will use, but i'd guess somewhere like 10 - 40% less than the full parameter training.

**Comment by drxmy** [comment]
Thank you！
