### ISSUE TITLE
Remove json intermediary for preprocessing datasets.

### ISSUE THREAD

**Issue by thomasw21** [bigscience-workshop/Megatron-DeepSpeed#41]
@stas00 suggested we might want to remove the whole json intermediary.

https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/18#issuecomment-892147586

This issue should be used to discuss if that's a feature we want, and if so, define clearly what we want.

**Comment by ontocord** [comment]
To make it efficient and work

ds = load_dataset("oscar", ...)

def process_sample_to_indexed_dataset(batch, indices):
   ...
   - create a builder based on the indices[0]. so something like XX_shard_<indices[0]>.bin, ....idx
   - do some tokenization
   - for b in tok_sequences:
          builder.add_item(b)

ds.map(process_sample_to_indexed_dataset, with_indices=True, num_proc = <number of cores>, batch_size = <round up of len(ds)/<number of cores>,...)
- then merge all the shard files?

**Comment by stas00** [comment]
> It would probably be slower than your queue based version of multi-processing. datasets uses apply_async to pass along the map_fn

My other concern is shuffling, which is slow in datasets. We currently use `terashuf` which is amazingly fast.

> You might want to delete all the arrow and downloaded files stuff after you create indexed_dataset to save disk space.

But this should be optional. Since if something went wrong, it'd be much faster to "resume" if datasets aren't wiped out. `datasets` recently added helper wrappers which can report the locations of the files, so it might be easier to just do it manually.

Perhaps, we just leave things as they are? We have a good process that is fast and it's done in stages, and can be resumed from each stage independently. It requires more attention/time from the operator than one script that does it all, but somehow I feel that since we do those things very infrequently, it's a solid process.

Or like with the faster with many cpu cores version, we have several versions and use the best one for the situation?

@thomasw21 - what do you think?

**Comment by sbmaruf** [comment]
According to my experience, iterating through the `HF dataset` API becomes slow when the dataset is large.
`json` is such a fundamental way of dealing with data. I would not vote for removing it, rather extend the preprocessing of text with HF-dataset APIs.
Hf-dataset has a lot of advantages though especially it handles caching and sharding internally. But still caching is a sequential process that takes a lot of time. I wonder if it evolves into caching from shards with multi-processing. That would be really great.

**Comment by ontocord** [comment]
I've worked with both HF-dataset and the current impl of JSONL + indexed_dataset.  In my project for the data-tooling, I'm trying to extend dataset to be able to work with things ike indexed_dataset, but that is still WIP. I vote for leaving good enough alone unless we have a compeling reason to change - like will it be an order of magnitude faster, or will it give us functionality we don't have. I've talked to @thomasw21 offline. One of the things we would want if we do retrieval is fulltext indexing on the JZ server itself, I would think. And HF dataset + elastic search (or some of the newer stuff I'm building with sqlite fts search) would do this. But if we are note doing retrieval, I would defer getting HF dataset working in megatron training pipeline.

**Comment by thomasw21** [comment]
> ds.map(process_sample_to_indexed_dataset, with_indices=True, num_proc = [number of cores], batch_size = [Some reasonable MB size],...)
> 
> * then merge all the shard files sorted by the number in  ...shard_[num].bin?
> 
> It would probably be slower than your queue based version of multi-processing. datasets uses apply_async to pass along the map_fn
> You might want to delete all the arrow and downloaded files stuff after you create indexed_dataset to save disk space.

Hum I'd say disk space is okay in JZ, since everything can move to scratch if need be. I'm also sure we can find a way to not use `.map` but my code instead. What I mean is essentially the process that loads all data in a queue, can instead of reading a file, read that dataset. So it wouldn't be that much slower compared to `jsonify` + `preprocess`.

> Perhaps, we just leave things as they are? We have a good process that is fast and it's done in stages, and can be resumed from each stage independently. It requires more attention/time from the operator than one script that does it all, but somehow I feel that since we do those things very infrequently, it's a solid process.

My argument would usually be, do we really need it? It's not clear to me yet that we'd obtain a faster preprocessing and by how much, depending on how arrow format works (TBD). But what I do know is that it's fairly easy to run `dataset.to_json` and then run preprocessing. So perhaps my two cent would be let's not do it until we need it? Basically what @ontocord said.

Consequently I believe we all agree not to do this right now. Let's close this issue then, and re-open if we ever find better argument in favor.

**Comment by stas00** [comment]
And then there was Adam with yet another take on pre-processing:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/48
