### ISSUE TITLE
implement GLU activation function

### ISSUE THREAD

**Issue by ibeltagy** [bigscience-workshop/Megatron-DeepSpeed#44]
Pick and implement one of the variants of the GLU activation.

Check here for comparison and equations
https://arxiv.org/pdf/2002.05202.pdf
https://arxiv.org/pdf/2102.11972.pdf

and here for implementation of one of them
https://github.com/EleutherAI/gpt-neox/blob/main/megatron/model/activations.py

**Comment by ibeltagy** [comment]
assigned to @jaketae

**Comment by jaketae** [comment]
Closed via #47, cc @ibeltagy
