### ISSUE TITLE
Rotary embeddings

### ISSUE THREAD

**Issue by thomasw21** [bigscience-workshop/Megatron-DeepSpeed#6]
# Description

Implement rotary embeddings:
 - paper: https://arxiv.org/pdf/2104.09864.pdf
 - code: https://github.com/ZhuiyiTechnology/roformer
 
 # Done
 
 - [ ] train a model using rotary embeddings

**Comment by ibeltagy** [comment]
@thomasw21, the code snippet here https://blog.eleuther.ai/rotary-embeddings/ should be easier to follow.

**Comment by thomasw21** [comment]
Ah but it looks like EleutherAI already implemented it in MegatronLM setup. https://github.com/EleutherAI/gpt-neox/blob/main/megatron/model/transformer.py#L340
