### ISSUE TITLE
unit test of fused softmax kernel

### ISSUE THREAD

**Issue by hyunwoongko** [bigscience-workshop/Megatron-DeepSpeed#61]
https://github.com/NVIDIA/Megatron-LM/issues/132

I've been looking at the megatron code nowadays. When using the softmax kernel used in megatron, it was observed that the results were different from the original torch softmax. How about doing a unit test on this kernel?

**Comment by thomasw21** [comment]
That'd be awesome! @stas00 is still currently setting up the UT. But feel free to contribute unit tests!

Concerning your issue with discrepancy between fused vs not fused, I'm wondering if it's not linked to `std::numeric_limits<acc_t>::infinity()` vs `-10000`

**Comment by hyunwoongko** [comment]
-10000 is not the value I set, it's the default value set by the Megatron LM. Also, even if the mask is changed from -10000 to -infinity, there is no padding in the encoder model (bert) setting, so no masking is applied.

**Comment by hyunwoongko** [comment]
My guess is there is something wrong with my test code or something with Megatron's kernel code. 
But I've looked all over the CUDA kernel code, and I can't find any problems with my test code.

**Comment by hyunwoongko** [comment]
Fused Softmax kernels have very limited operating conditions. The batch_per_block (warps_per_block * batches_per_warp) should be divided by the length of the query, and the length of the key should be divided by 4. There are many other conditions. So in general, this kernel will not work. However, if certain conditions are met, this kernel will work.

**Comment by stas00** [comment]
> That'd be awesome! @stas00 is still currently setting up the UT framework. But feel free to contribute unit tests!

It's done: https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/64

Feel free to add new tests.

**Comment by hyunwoongko** [comment]
https://github.com/NVIDIA/Megatron-LM/commit/2387ce01c91e5ddcb91d86a335d993e0a664b9dd

There was a problem with the kernel. This has been fixed and merged into the main branch of megatron lm.
